### ISSUE TITLE
BioModel Discussion Issue for eos4e40

### ISSUE THREAD

**Issue by Zainab-ik** [ersilia-os/eos4e40#7]
**Summary !!!**

- **BioModel Name**: Stokes2020 -  Antibiotics discovery using deep learning approach.

- **BioModel Tag**: fair AIML, Machine learning model

- **Metadata Comments**: 
1. _Halicin_ was discovered with the DNN model, as an important part of the paper, would it be an important metadata?And which category (property or output)? 
2. _Halicin_ has bactericidal activity against _Mycobacterium tuberculosis_ and _carbapenem-resistant Enterobacteriaceae_, do they classify as biological properties of the model. 

- **Contributor**:

> 
 | roles             | Names | 
 | :---------------- | :------: | 
 | Curator        |   @Zainab-ik   | 
 | Modeller       |   @miquelduranfrigola      | 
 | Reviewer       |   @GemmaTuron    | 

- **Curation status** :  manually curated

- **Annotation file**: [here](https://docs.google.com/spreadsheets/d/1J05kXGK1FoeZbQlbNuU5y0wb_puDi4-5a-X0a8VXb78/edit?usp=drive_link)

**Comment by miquelduranfrigola** [comment]
Thanks @Zainab-ik - I don't think Halicin is important for this model's metadata. What do you think, @GemmaTuron ?

**Comment by GemmaTuron** [comment]
Hi @Zainab-ik 

Good questions:
- Halicin is just a research finding when using the model, I would not describe it as metadata for the model
- In this case, the authors specifically use an E.coli inhibition assay to get the training data, so I would add E.coli only as the organism. The fact that they then test against other bacteria is independent from the model itself, if that makes sense

**Comment by Zainab-ik** [comment]
Since Halicin is just a discovery of the model and it was validated using those bacteria. They aren't part of the model itself. 
That makes perfect sense.

**Comment by GemmaTuron** [comment]
This is completed
